### ISSUE TITLE
[Bug] Chisel n Bit's JEI compatibility is broken

### ISSUE THREAD

**Issue by aaronhowser1** [shedaniel/RoughlyEnoughItems#665]
**Describe the bug**
In `chiselsandbits-client.toml`: 
```toml
	#Compatibility options for JEI.
	[compat.jei]
		#Should C&B inject its bits into JEI?
		inject-bits = false
```
![image](https://user-images.githubusercontent.com/15698722/142988796-99b6e820-bb81-4ebe-b065-9b6a447cb5c1.png)

**Environment (please complete the following information with the version):**
 - Minecraft: 1.16.5
 - Mod Loader: Forge
